on:
  workflow_call:
    inputs:
      artifactPattern:
        required: true
        type: string
        default: "release-packages-*"
        description: "Pattern to match the artifact names to download"
      environment:
        required: true
        type: string
        default: "nuget-production"
        description: "Environment name for manual approval (must be configured in repository settings)"
      runId:
        required: true
        type: string
        description: "ID of the workflow run to download artifacts from"
      workflowName:
        required: true
        type: string
        default: "ci-dotnet.yml"
        description: "Name of the workflow to check for successful builds"
    secrets:
      NUGET_TOKEN:
        required: true
      WORKFLOW_PACKAGES:
        required: true

jobs:
  nuget:
    name: Publish NuGet Packages
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    steps:
      - name: Download artifacts from `${{ inputs.workflowName }}` workflow
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          github-token: ${{ secrets.WORKFLOW_PACKAGES }}
          merge-multiple: true
          path: packages
          pattern: ${{ inputs.artifactPattern }}
          run-id: ${{ inputs.runId }}

      - name: Publish NuGet Package
        run: |
          dotnet nuget push packages/**/*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json --skip-duplicate
